#!/usr/bin/env bash
# Finish mode (§6): commit staged changes, push, and open a PR if the branch
# doesn't already have one. The model supplies the commit message and PR body
# (judgment); this script does the deterministic git/gh ceremony.
#
# Usage: finish.sh <issue#> <pr-title> <commit-msg-file> <pr-body-file>
#
#   - Commits ONLY what is already staged. Stage the issue's files first.
#   - If nothing is staged, the commit is skipped and existing commits are pushed.
#   - If a PR already exists for the branch, the push updates it (no new PR) and
#     this run's PR body is appended to the description as an "### Update" section.
#   - PRs are created NOT as drafts.
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$DIR/lib.sh"

num="${1:?issue number required}"
title="${2:?PR title required}"
msgfile="${3:?commit message file required}"
bodyfile="${4:?PR body file required}"

branch=$(git branch --show-current)
[ -n "$branch" ] && [ "$branch" != "main" ] || {
	echo "Refusing to finish on '$branch' — switch to a feature branch first." >&2
	exit 1
}

# Attribution is always the current git user — never hardcoded, never Claude.
author=$(git config user.name || true)
[ -n "$author" ] || author="current user"

# Append "Generated by <author>" to a copy of the given file (idempotent).
with_attribution() {
	local src="$1" out
	out=$(mktemp)
	cat "$src" >"$out"
	if ! grep -qi "^Generated by " "$out"; then
		printf '\n\nGenerated by %s\n' "$author" >>"$out"
	fi
	echo "$out"
}

if git diff --cached --quiet; then
	echo "Nothing staged — skipping commit, pushing existing commits on $branch."
else
	[ -s "$msgfile" ] || { echo "Commit message file '$msgfile' is empty." >&2; exit 1; }
	git commit -F "$(with_attribution "$msgfile")"
fi

git push -u origin "$branch"

pr=$(gh pr list --repo "$REPO" --head "$branch" --json number,url --jq '.[0] | "\(.number)\t\(.url)" // empty')
if [ -n "$pr" ]; then
	number=${pr%%$'\t'*}
	url=${pr#*$'\t'}
	if [ -s "$bodyfile" ]; then
		# Append this run's write-up to the existing PR description (keep prior context).
		curbody=$(gh pr view "$number" --repo "$REPO" --json body --jq '.body')
		combined=$(mktemp)
		{
			printf '%s\n' "$curbody"
			printf '\n\n---\n\n### Update\n\n'
			cat "$bodyfile"
			printf '\n\nGenerated by %s\n' "$author"
		} >"$combined"
		gh pr edit "$number" --repo "$REPO" --body-file "$combined" >/dev/null
		echo "PR already exists — push updated it and appended an Update section: $url"
	else
		echo "PR already exists — push updated it: $url"
	fi
else
	[ -s "$bodyfile" ] || { echo "PR body file '$bodyfile' is empty." >&2; exit 1; }
	url=$(gh pr create --repo "$REPO" --base main --head "$branch" \
		--title "$title" --body-file "$(with_attribution "$bodyfile")" | tail -1)
	echo "Opened PR: $url"
fi
