export interface Surah {
	number: number;
	nameAr: string;
	nameEn: string;
	verses: number;
}

export const SURAHS: Surah[] = [
	{ number: 1, nameAr: "الفاتحة", nameEn: "Al-Fatiha", verses: 7 },
	{ number: 2, nameAr: "البقرة", nameEn: "Al-Baqarah", verses: 286 },
	{ number: 3, nameAr: "آل عمران", nameEn: "Aal-Imran", verses: 200 },
	{ number: 4, nameAr: "النساء", nameEn: "An-Nisa", verses: 176 },
	{ number: 5, nameAr: "المائدة", nameEn: "Al-Ma'idah", verses: 120 },
	{ number: 6, nameAr: "الأنعام", nameEn: "Al-An'am", verses: 165 },
	{ number: 7, nameAr: "الأعراف", nameEn: "Al-A'raf", verses: 206 },
	{ number: 8, nameAr: "الأنفال", nameEn: "Al-Anfal", verses: 75 },
	{ number: 9, nameAr: "التوبة", nameEn: "At-Tawbah", verses: 129 },
	{ number: 10, nameAr: "يونس", nameEn: "Yunus", verses: 109 },
	{ number: 11, nameAr: "هود", nameEn: "Hud", verses: 123 },
	{ number: 12, nameAr: "يوسف", nameEn: "Yusuf", verses: 111 },
	{ number: 13, nameAr: "الرعد", nameEn: "Ar-Ra'd", verses: 43 },
	{ number: 14, nameAr: "إبراهيم", nameEn: "Ibrahim", verses: 52 },
	{ number: 15, nameAr: "الحجر", nameEn: "Al-Hijr", verses: 99 },
	{ number: 16, nameAr: "النحل", nameEn: "An-Nahl", verses: 128 },
	{ number: 17, nameAr: "الإسراء", nameEn: "Al-Isra", verses: 111 },
	{ number: 18, nameAr: "الكهف", nameEn: "Al-Kahf", verses: 110 },
	{ number: 19, nameAr: "مريم", nameEn: "Maryam", verses: 98 },
	{ number: 20, nameAr: "طه", nameEn: "Ta-Ha", verses: 135 },
	{ number: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiya", verses: 112 },
	{ number: 22, nameAr: "الحج", nameEn: "Al-Hajj", verses: 78 },
	{ number: 23, nameAr: "المؤمنون", nameEn: "Al-Mu'minun", verses: 118 },
	{ number: 24, nameAr: "النور", nameEn: "An-Nur", verses: 64 },
	{ number: 25, nameAr: "الفرقان", nameEn: "Al-Furqan", verses: 77 },
	{ number: 26, nameAr: "الشعراء", nameEn: "Ash-Shu'ara", verses: 227 },
	{ number: 27, nameAr: "النمل", nameEn: "An-Naml", verses: 93 },
	{ number: 28, nameAr: "القصص", nameEn: "Al-Qasas", verses: 88 },
	{ number: 29, nameAr: "العنكبوت", nameEn: "Al-Ankabut", verses: 69 },
	{ number: 30, nameAr: "الروم", nameEn: "Ar-Rum", verses: 60 },
	{ number: 31, nameAr: "لقمان", nameEn: "Luqman", verses: 34 },
	{ number: 32, nameAr: "السجدة", nameEn: "As-Sajdah", verses: 30 },
	{ number: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzab", verses: 73 },
	{ number: 34, nameAr: "سبأ", nameEn: "Saba", verses: 54 },
	{ number: 35, nameAr: "فاطر", nameEn: "Fatir", verses: 45 },
	{ number: 36, nameAr: "يس", nameEn: "Ya-Sin", verses: 83 },
	{ number: 37, nameAr: "الصافات", nameEn: "As-Saffat", verses: 182 },
	{ number: 38, nameAr: "ص", nameEn: "Sad", verses: 88 },
	{ number: 39, nameAr: "الزمر", nameEn: "Az-Zumar", verses: 75 },
	{ number: 40, nameAr: "غافر", nameEn: "Ghafir", verses: 85 },
	{ number: 41, nameAr: "فصلت", nameEn: "Fussilat", verses: 54 },
	{ number: 42, nameAr: "الشورى", nameEn: "Ash-Shura", verses: 53 },
	{ number: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", verses: 89 },
	{ number: 44, nameAr: "الدخان", nameEn: "Ad-Dukhan", verses: 59 },
	{ number: 45, nameAr: "الجاثية", nameEn: "Al-Jathiyah", verses: 37 },
	{ number: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", verses: 35 },
	{ number: 47, nameAr: "محمد", nameEn: "Muhammad", verses: 38 },
	{ number: 48, nameAr: "الفتح", nameEn: "Al-Fath", verses: 29 },
	{ number: 49, nameAr: "الحجرات", nameEn: "Al-Hujurat", verses: 18 },
	{ number: 50, nameAr: "ق", nameEn: "Qaf", verses: 45 },
	{ number: 51, nameAr: "الذاريات", nameEn: "Adh-Dhariyat", verses: 60 },
	{ number: 52, nameAr: "الطور", nameEn: "At-Tur", verses: 49 },
	{ number: 53, nameAr: "النجم", nameEn: "An-Najm", verses: 62 },
	{ number: 54, nameAr: "القمر", nameEn: "Al-Qamar", verses: 55 },
	{ number: 55, nameAr: "الرحمن", nameEn: "Ar-Rahman", verses: 78 },
	{ number: 56, nameAr: "الواقعة", nameEn: "Al-Waqi'ah", verses: 96 },
	{ number: 57, nameAr: "الحديد", nameEn: "Al-Hadid", verses: 29 },
	{ number: 58, nameAr: "المجادلة", nameEn: "Al-Mujadilah", verses: 22 },
	{ number: 59, nameAr: "الحشر", nameEn: "Al-Hashr", verses: 24 },
	{ number: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahanah", verses: 13 },
	{ number: 61, nameAr: "الصف", nameEn: "As-Saff", verses: 14 },
	{ number: 62, nameAr: "الجمعة", nameEn: "Al-Jumu'ah", verses: 11 },
	{ number: 63, nameAr: "المنافقون", nameEn: "Al-Munafiqun", verses: 11 },
	{ number: 64, nameAr: "التغابن", nameEn: "At-Taghabun", verses: 18 },
	{ number: 65, nameAr: "الطلاق", nameEn: "At-Talaq", verses: 12 },
	{ number: 66, nameAr: "التحريم", nameEn: "At-Tahrim", verses: 12 },
	{ number: 67, nameAr: "الملك", nameEn: "Al-Mulk", verses: 30 },
	{ number: 68, nameAr: "القلم", nameEn: "Al-Qalam", verses: 52 },
	{ number: 69, nameAr: "الحاقة", nameEn: "Al-Haqqah", verses: 52 },
	{ number: 70, nameAr: "المعارج", nameEn: "Al-Ma'arij", verses: 44 },
	{ number: 71, nameAr: "نوح", nameEn: "Nuh", verses: 28 },
	{ number: 72, nameAr: "الجن", nameEn: "Al-Jinn", verses: 28 },
	{ number: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", verses: 20 },
	{ number: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", verses: 56 },
	{ number: 75, nameAr: "القيامة", nameEn: "Al-Qiyamah", verses: 40 },
	{ number: 76, nameAr: "الإنسان", nameEn: "Al-Insan", verses: 31 },
	{ number: 77, nameAr: "المرسلات", nameEn: "Al-Mursalat", verses: 50 },
	{ number: 78, nameAr: "النبأ", nameEn: "An-Naba", verses: 40 },
	{ number: 79, nameAr: "النازعات", nameEn: "An-Nazi'at", verses: 46 },
	{ number: 80, nameAr: "عبس", nameEn: "Abasa", verses: 42 },
	{ number: 81, nameAr: "التكوير", nameEn: "At-Takwir", verses: 29 },
	{ number: 82, nameAr: "الانفطار", nameEn: "Al-Infitar", verses: 19 },
	{ number: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", verses: 36 },
	{ number: 84, nameAr: "الانشقاق", nameEn: "Al-Inshiqaq", verses: 25 },
	{ number: 85, nameAr: "البروج", nameEn: "Al-Buruj", verses: 22 },
	{ number: 86, nameAr: "الطارق", nameEn: "At-Tariq", verses: 17 },
	{ number: 87, nameAr: "الأعلى", nameEn: "Al-A'la", verses: 19 },
	{ number: 88, nameAr: "الغاشية", nameEn: "Al-Ghashiyah", verses: 26 },
	{ number: 89, nameAr: "الفجر", nameEn: "Al-Fajr", verses: 30 },
	{ number: 90, nameAr: "البلد", nameEn: "Al-Balad", verses: 20 },
	{ number: 91, nameAr: "الشمس", nameEn: "Ash-Shams", verses: 15 },
	{ number: 92, nameAr: "الليل", nameEn: "Al-Layl", verses: 21 },
	{ number: 93, nameAr: "الضحى", nameEn: "Ad-Duha", verses: 11 },
	{ number: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", verses: 8 },
	{ number: 95, nameAr: "التين", nameEn: "At-Tin", verses: 8 },
	{ number: 96, nameAr: "العلق", nameEn: "Al-Alaq", verses: 19 },
	{ number: 97, nameAr: "القدر", nameEn: "Al-Qadr", verses: 5 },
	{ number: 98, nameAr: "البينة", nameEn: "Al-Bayyinah", verses: 8 },
	{ number: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzalah", verses: 8 },
	{ number: 100, nameAr: "العاديات", nameEn: "Al-Adiyat", verses: 11 },
	{ number: 101, nameAr: "القارعة", nameEn: "Al-Qari'ah", verses: 11 },
	{ number: 102, nameAr: "التكاثر", nameEn: "At-Takathur", verses: 8 },
	{ number: 103, nameAr: "العصر", nameEn: "Al-Asr", verses: 3 },
	{ number: 104, nameAr: "الهمزة", nameEn: "Al-Humazah", verses: 9 },
	{ number: 105, nameAr: "الفيل", nameEn: "Al-Fil", verses: 5 },
	{ number: 106, nameAr: "قريش", nameEn: "Quraysh", verses: 4 },
	{ number: 107, nameAr: "الماعون", nameEn: "Al-Ma'un", verses: 7 },
	{ number: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", verses: 3 },
	{ number: 109, nameAr: "الكافرون", nameEn: "Al-Kafirun", verses: 6 },
	{ number: 110, nameAr: "النصر", nameEn: "An-Nasr", verses: 3 },
	{ number: 111, nameAr: "المسد", nameEn: "Al-Masad", verses: 5 },
	{ number: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlas", verses: 4 },
	{ number: 113, nameAr: "الفلق", nameEn: "Al-Falaq", verses: 5 },
	{ number: 114, nameAr: "الناس", nameEn: "An-Nas", verses: 6 },
];

export function getSurahName(number: number, language: string): string {
	const surah = SURAHS.find((s) => s.number === number);
	if (!surah) return "";
	return language === "ar" ? surah.nameAr : surah.nameEn;
}

/**
 * First mushaf page of each surah in the standard Madani 604-page mushaf
 * (indexed by surah number). Used to label a page with the surah it falls in,
 * since the app is now entirely page-based.
 */
export const SURAH_START_PAGES: Record<number, number> = {
	1: 1,
	2: 2,
	3: 50,
	4: 77,
	5: 106,
	6: 128,
	7: 151,
	8: 177,
	9: 187,
	10: 208,
	11: 221,
	12: 235,
	13: 249,
	14: 255,
	15: 262,
	16: 267,
	17: 282,
	18: 293,
	19: 305,
	20: 312,
	21: 322,
	22: 332,
	23: 342,
	24: 350,
	25: 359,
	26: 367,
	27: 377,
	28: 385,
	29: 396,
	30: 404,
	31: 411,
	32: 415,
	33: 418,
	34: 428,
	35: 434,
	36: 440,
	37: 446,
	38: 453,
	39: 458,
	40: 467,
	41: 477,
	42: 483,
	43: 489,
	44: 496,
	45: 499,
	46: 502,
	47: 507,
	48: 511,
	49: 515,
	50: 518,
	51: 520,
	52: 523,
	53: 526,
	54: 528,
	55: 531,
	56: 534,
	57: 537,
	58: 542,
	59: 545,
	60: 549,
	61: 551,
	62: 553,
	63: 554,
	64: 556,
	65: 558,
	66: 560,
	67: 562,
	68: 564,
	69: 566,
	70: 568,
	71: 570,
	72: 572,
	73: 574,
	74: 575,
	75: 577,
	76: 578,
	77: 580,
	78: 582,
	79: 583,
	80: 585,
	81: 586,
	82: 587,
	83: 587,
	84: 589,
	85: 590,
	86: 591,
	87: 591,
	88: 592,
	89: 593,
	90: 594,
	91: 595,
	92: 595,
	93: 596,
	94: 596,
	95: 597,
	96: 597,
	97: 598,
	98: 598,
	99: 599,
	100: 599,
	101: 600,
	102: 600,
	103: 601,
	104: 601,
	105: 601,
	106: 602,
	107: 602,
	108: 602,
	109: 603,
	110: 603,
	111: 603,
	112: 604,
	113: 604,
	114: 604,
};

/** First mushaf page of a surah (1 if unknown). */
export function getStartPageForSurah(surah: number): number {
	return SURAH_START_PAGES[surah] ?? 1;
}

/** The surah a page belongs to — the last surah whose start page is ≤ `page`. */
export function getSurahNumberForPage(page: number): number {
	let result = 1;
	for (const s of SURAHS) {
		if ((SURAH_START_PAGES[s.number] ?? 1) <= page) result = s.number;
		else break;
	}
	return result;
}

/** Name of the surah a page falls in. */
export function getSurahNameForPage(page: number, language: string): string {
	return getSurahName(getSurahNumberForPage(page), language);
}

/**
 * Human label for the surah(s) a page range spans: a single name when start and
 * end fall in the same surah, otherwise "first – last".
 */
export function getSurahNamesForPageRange(
	startPage: number,
	endPage: number,
	language: string,
): string {
	const first = getSurahNumberForPage(startPage);
	const last = getSurahNumberForPage(endPage);
	if (first === last) return getSurahName(first, language);
	return `${getSurahName(first, language)} – ${getSurahName(last, language)}`;
}
